
project_id = "dyefbzcbphkgyapwmzwm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173"

[realtime]
enabled = true

[functions.add_service_message]
verify_jwt = true

[functions.send-invite]
verify_jwt = true

[storage]
enabled = true
