
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './schema';

const SUPABASE_URL = "https://dyefbzcbphkgyapwmzwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZWZiemNicGhrZ3lhcHdtendtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDczMjYsImV4cCI6MjA1Nzc4MzMyNn0.r2mCuEZEYnrTGa_HkkAQlEANCZ9Wseiyu-HS8kUIIuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'supabase-auth',
  }
});
